import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'

import Header from './header'
import Aside from './aside'

import styled from 'styled-components'


const Container = styled.main`
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    height: 100vh;
`

const MainContent = styled.div`
    flex: 1;
    display: flex;
    flex-direction: row;

    &>div:last-child{
      flex: 1;
      padding: 3rem ${({theme})=>theme?.margin?.default} 3rem 3rem;
    }

    &>div:last-child>div:first-child{
      display: flex;
      flex-direction: row;
      align-items: center;
      margin-bottom: 1.5rem;
    }
    &>div:last-child>div:first-child span{
      margin-right: 1rem;
      font-size: 16pt;
    }
    &>div:last-child>div:first-child h1{
      font-weight: normal !important;
      margin: 0;
      color: ${({theme})=>theme?.colors?.primary};
      font-size: 16pt;
    }
`

const View: NextPage = ({ children }) => {
  
  const [route, setRoute] = useState<Route>()

  return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
          <Header />
          <MainContent>
            <Aside getRoute={route => setRoute(route)} />
            <div>
              <div>
                {route?.icon}
                <h1>{route?.title}</h1>
              </div>
              <div>
                {children}
              </div>
            </div>
          </MainContent>
        </Container>
      </div>
  )
}

export default View
